version: "3"
services:
  api:
    image: rjcortese/alligator:latest
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "8080:80"
  db:
    image: mongo:latest
    env_file:
      - ./db/.env
    expose:
      - "27017"
    volumes:
      - "db-data:/data/db"
      - "db-conf:/data/configdb"

volumes:
  db-data:
  db-conf:
