version: 3.8
services:
  api:
    image: alligator
    build: ./api
    ports:
      - "8080:80"

  mysql:
    image: mysql/mysql-server:latest
    volumes:
      - "mysql-data:/var/lib/mysql"
  expose:
    - "3306"

volumes:
  mysql-data:

